module.exports = {
    batchReadJsonConfigure: require('./batch-read-json.configure'),
    batchWriteConfigure: require('./batch-write.configure'),
    rewriteJsonLikeConfigure: require('./rewrite-json-like.configure'),
    assertExistsSync: require('./assert-exists-sync'),
    batchReadJson: require('./batch-read-json'),
    batchWrite: require('./batch-write'),
    configure: require('./configure'),
    detectFileSystem: require('./detect-file-system'),
    detectLinux: require('./detect-linux'),
    detectMacos: require('./detect-macos'),
    detectWindows: require('./detect-windows'),
    isDirEmpty: require('./is-dir-empty'),
    mkdirp: require('./mkdirp'),
    readJson: require('./read-json'),
    readJsonDir: require('./read-json-dir'),
    readJsonLike: require('./read-json-like'),
    readTextSwapExtSync: require('./read-text-swap-ext-sync'),
    remkdir: require('./remkdir'),
    rename: require('./rename'),
    rewriteJsonLike: require('./rewrite-json-like'),
    writeJson: require('./write-json'),
    writeJsonDir: require('./write-json-dir'),
    writeJsonLike: require('./write-json-like')
};
