module.exports = {

    indent: 4,
    delimiter: ',',
    pathDelimiter: '/',
    locationData: { cities: [], states: [], countries: [] },

    videoMajorBrands: ['mp42', 'qt', 'isom'],
    videoFileTypes: ['mp4', 'mov', 'avi', 'mkv', 'webm', '3gp', 'mts', 'm4v'],

    smartDeviceBrands: [
        'Apple',
        'Samsung',
        'Google',
        'Xiaomi',
        'HUAWEI',
        'Sony',
        'LG',
        'OnePlus',
        'OPPO',
        'vivo',
        'realme',
        'motorola',
        'Nokia',
        'ASUS',
        'Lenovo',
        'HONOR',
        'ZTE',
        'TECNO',
        'Infinix',
        'Nothing'
    ],

    accentReplacements: {
        A: ['À', 'Á', 'Â', 'Ã', 'Ä', 'Å'],
        a: ['à', 'á', 'â', 'ã', 'ä', 'å'],
        E: ['È', 'É', 'Ê', 'Ë'],
        e: ['è', 'é', 'ê', 'ë'],
        I: ['Ì', 'Í', 'Î', 'Ï'],
        i: ['ì', 'í', 'î', 'ï'],
        O: ['Ò', 'Ó', 'Ô', 'Õ', 'Ö', 'Ō', 'Ø'],
        o: ['ò', 'ó', 'ô', 'õ', 'ö', 'ō', 'ø'],
        U: ['Ù', 'Ú', 'Û', 'Ü'],
        u: ['ù', 'ú', 'û', 'ü'],
        C: ['Ç'],
        c: ['ç'],
        N: ['Ñ'],
        n: ['ñ'],
        AE: ['Æ'],
        ae: ['æ'],
        OE: ['Œ'],
        oe: ['œ'],
        L: ['Ł'],
        l: ['ł'],
        S: ['Š', 'Ś'],
        s: ['š', 'ś'],
        Z: ['Ž'],
        z: ['ž'],
        R: ['Ř'],
        r: ['ř'],
        D: ['Đ'],
        d: ['đ'],
        Y: ['Ÿ'],
        y: ['ÿ']
    }

};
